enum {
	LOOKUP_BITS = 8,
	EXP_POS = 23,
	EXP_BIAS = 127,
	LOOKUP_POS = EXP_POS - LOOKUP_BITS,
	SEED_POS = EXP_POS - LOOKUP_BITS,
	SQRT_TABLE_SIZE = 2 << LOOKUP_BITS,
	LOOKUP_MASK = SQRT_TABLE_SIZE - 1,
};

int enum_sum() {
	return LOOKUP_BITS + EXP_POS + EXP_BIAS + LOOKUP_POS + SEED_POS + SQRT_TABLE_SIZE + LOOKUP_MASK;
}
